[package]
name = "mal"
version = "0.1.0"
authors = ["jordi.inyigo"]
edition = "2024"

[lib]
name = "mal"
path = "lib.rs"

[dependencies]
itertools = "0.13"
fnv = "1.0.6"
scanner = { git = "https://github.com/jig/scanner-rust", version = "0.1.1" }

[dev-dependencies]
rustyline = "14.0"
