[package]
name = "mal"
version = "0.1.0"
authors = ["root"]
edition = "2024"

[lib]
name = "mal"
path = "lib.rs"

[[bin]]
name = "mal"
path = "main.rs"

[dependencies]
rustyline = "14.0"
regex = "1.7"
itertools = "0.13"
fnv = "1.0.6"
